# Generated by Django 5.0.6 on 2024-05-17 04:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home_page', '0002_comlogin_remove_comsingup_state'),
    ]

    operations = [
        migrations.CreateModel(
            name='Candidatelogin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('password', models.CharField(max_length=122)),
            ],
        ),
        migrations.AlterField(
            model_name='comsingup',
            name='phone',
            field=models.CharField(max_length=14),
        ),
    ]
