# Generated by Django 5.0.6 on 2024-05-18 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home_page', '0003_candidatelogin_alter_comsingup_phone'),
    ]

    operations = [
        migrations.CreateModel(
            name='Candidatesingup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('password', models.CharField(max_length=122)),
                ('username', models.CharField(max_length=122)),
                ('education', models.CharField(max_length=122)),
                ('address', models.CharField(max_length=122)),
                ('phone', models.CharField(max_length=14)),
                ('city', models.CharField(max_length=122)),
                ('fileinput', models.CharField(max_length=122)),
            ],
        ),
    ]
