# Generated by Django 5.0.6 on 2024-05-18 11:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home_page', '0005_rename_fileinput_candidatesingup_file_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='candidatesingup',
            old_name='address',
            new_name='institution',
        ),
    ]
